/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SummarizerFrame.java
 *
 * Created on 2012-maj-02, 16:09:00
 */

package merge.pdfstod.GUI;

// import cogsum.CogSum;
/* import cogsum.Settings;
import easyreader.Document;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane; */



/**
 *
 * @author Allan
 */
public class SummarizerFrame extends javax.swing.JFrame {

    private PDFReader pdfreader = null;
    public static int sumslidval = 0;

    /** Creates new form SummarizerFrame */
    public SummarizerFrame( PDFReader pdfr) // Boolean showComp)
    {
        initComponents();

        // this.setSize(100, 30); //AH* tillagd.
        setPreferredSize(new java.awt.Dimension(500, 70));
        // summarizer = new CogSum(new Settings());
        // if (!showComp) //AH* Nytillagt 120423
        {
            VäljMening.setVisible(true);
            ValdMening.setVisible(true);
            startBtn.setVisible(true);
            TFSlider.setVisible(true);
        }
        pdfreader = pdfr;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TFSlider = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ValdMening = new javax.swing.JTextField();
        startBtn = new javax.swing.JButton();
        VäljMening = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TFSlider.setText("100");
        TFSlider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSliderActionPerformed(evt);
            }
        });

        jLabel1.setText("Ange vald mening och eller sammanfattningsnivå i %.");

        ValdMening.setText("0");

        startBtn.setText("Start");
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
        });

        VäljMening.setText("Meningsnr");
        VäljMening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VäljMeningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(VäljMening)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ValdMening, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValdMening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VäljMening)
                    .addComponent(TFSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFSliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSliderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSliderActionPerformed

    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
        // outputWindow.setText(""); AH*
//        System.out.println("Startknappen tryckt.");
        // sumslidval = summarySlider.getModel().getValue();
        sumslidval = str2int( TFSlider.getText() );
        if (sumslidval > 100) sumslidval = 100;
//        System.out.println("Slider värde: " + sumslidval);
        pdfreader.UppdateraSammanfatta( sumslidval, pdfreader.currentPage, -1 );
//        System.out.println("Efter Startknappen.");
        /*
        Document d = new Document();
        // AH* d.read(new StringBuffer(this.inputWindow.getText()));
        this.summarizer.setText(d);
        this.summarizer.buildSummary();
         *
         */

        // AH* outputWindow.setText(this.summarizer.retrieveSummary(30,false));
}//GEN-LAST:event_startBtnMouseClicked

    private void VäljMeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VäljMeningActionPerformed
        // TODO add your handling code here:
        int valdmennr = 0;
        valdmennr = str2int( ValdMening.getText() );
        System.out.println("VäljMening tryckt.");
        sumslidval = str2int( TFSlider.getText() );
        if (sumslidval > 100) sumslidval = 100;
        System.out.println("Slider värde: " + sumslidval);
        System.out.println("Vald mening: " + valdmennr);
        pdfreader.UppdateraSammanfatta( sumslidval, pdfreader.currentPage, valdmennr );
        System.out.println("Efter VäljMening.");
}//GEN-LAST:event_VäljMeningActionPerformed

        private int str2int(String instr)
    {
        int k;
        int summa = 0;
        int nolla = (int)'0';
        for (k=0;k<instr.length(); k++)
        {
            if ((instr.charAt(k)>= '0')&&(instr.charAt(k)<='9'))
            {
                summa = summa*10 + (int)instr.charAt(k) - nolla;
            } else
            {
                System.out.println("Ej siffra i sidfältet.");
                return 0;
            }
        }
        return summa;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new SummarizerFrame().setVisible(true); AH* ändrad.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFSlider;
    private javax.swing.JTextField ValdMening;
    private javax.swing.JButton VäljMening;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables

}
