/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2010-nov-10, 12:34:04
 */

package merge.summarization.easyreader.GUI;

import javax.swing.JFileChooser;
import merge.summarization.easyreader.reader.SummaryReader;

/**
 *
 * @author Christian
 */
public class ReaderFrame extends javax.swing.JFrame {
    private String inFile;
    private SummaryReader reader;
    final JFileChooser fileChooser = new JFileChooser();
    /** Creates new form MainFrame */
    public ReaderFrame() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        summariesPanel = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        summariesPanel.setBackground(new java.awt.Color(204, 204, 204));
        summariesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("\"filename\"");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${inFile}"), jLabel1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(summariesPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .add(6, 6, 6)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(summariesPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButton1)
                        .add(jButton2))
                    .add(jLabel1))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private SummarizerWindowPanel2 newSumWindow(){
//
//        SummarizerWindowPanel2 swp = new SummarizerWindowPanel2();
////        swp.setVisible(true);
//        
//        JInternalFrame frame = new JInternalFrame("Sum",true,true,true);
////        frame.setClosable(true);
//        frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
////        frame.setResizable(true);
//        frame.add(swp);
//        frame.setVisible(true);
//        frame.pack();
//
//        this.summariesPanel.add(frame);
//        this.summariesPanel.validate();
//        validate();
//        
//        return swp;
//    }
//
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        Summary summ = sum.buildSummary();
//        Summary summ = SummaryXMLReader.read("out.xml");

//        SummaryReader reader = new SummaryReader(summ);

        // TODO add your handling code here:
        int retVal = fileChooser.showOpenDialog(this);

        if(retVal == JFileChooser.APPROVE_OPTION){
            inFile = fileChooser.getSelectedFile().toString();
            this.jLabel1.setText(inFile);
            System.out.println(fileChooser.getSelectedFile());



        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//         TODO add your handling code here:
//        Document d = new Document();
//
//        if(inFile != null)
//            d.readFile(inFile);
//
//        Settings s = new Settings();
//        s.setDimensionality(100);
//        s.setUseOutsideSpace(false);
//        s.setTrainingFile("brown_training/news1");
//        
//        s.setRemoveDocumentVector(true);
//        s.setRemoveStopWords(false);
//        CogSum cs = new CogSum(s);
//        cs.setText(d);
//        Summary summ = cs.buildSummary();
//        summ.save("out.xml");
//
//        reader = new SummaryReader(summ);
//
//
//        SummarizerWindowPanel2 p = newSumWindow();
//        p.setReader(reader);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReaderFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane summariesPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
